### ISSUE TITLE
Compose-Multiplatform-Wizard Both the wasm and JS configurations fail. npm

### ISSUE THREAD

**Issue by mylockerbiz** [terrakok/Compose-Multiplatform-Wizard#59]
Konstantin,
I have been trying to convert my app to KMP for about a month. I have tried around 15 different templates or project conversions but without success. They will all work for one platform but not another.
I used your wizard and (https://terrakok.github.io/Compose-Multiplatform-Wizard/) for all five platforms and selected 
Coroutines, serialization DateTime and Kstore.
I put these into my Android Studio and to my great and pleasant surprise android and desktop work without issue.
 
Both the wasm and JS configurations fail.
I have installed and updated NPM to v22.3.0 and the directory still shows v22.0.0 (C:\Users\envy\.gradle\nodejs\node-v22.0.0-win-x64)
 
This is from the Build Output console 
npm ERR! code EISDIR
npm ERR! syscall symlink
npm ERR! path D:\OWJ\androidStudio-mulitplatform\Multiplatform-App\build\js\packages_imported\skiko-wasm-js\0.8.4
npm ERR! dest D:\OWJ\androidStudio-mulitplatform\Multiplatform-App\build\js\node_modules\skiko-wasm-js
npm ERR! errno -4068
npm ERR! EISDIR: illegal operation on a directory, symlink 'D:\OWJ\androidStudio-mulitplatform\Multiplatform-App\build\js\packages_imported\skiko-wasm-js\0.8.4' -> 'D:\OWJ\androidStudio-mulitplatform\Multiplatform-App\build\js\node_modules\skiko-wasm-js'
 
npm ERR! A complete log of this run can be found in: C:\Users\envy\AppData\Local\npm-cache\_logs\2024-06-16T21_25_51_706Z-debug-0.log
 
> Task :kotlinNpmInstall FAILED
 
Execution failed for task ':kotlinNpmInstall'.
> Process 'Resolving NPM dependencies using npm' returns -4068
 
 
This is from the log file
2365 verbose stack Error: EISDIR: illegal operation on a directory, symlink 'D:\OWJ\androidStudio-mulitplatform\Multiplatform-App\build\js\packages_imported\skiko-wasm-js\0.8.4' -> 'D:\OWJ\androidStudio-mulitplatform\Multiplatform-App\build\js\node_modules\skiko-wasm-js'
2365 verbose stack     at async symlink (node:internal/fs/promises:1002:10)
2365 verbose stack     at async [extractOrLink] (C:\Users\envy\.gradle\nodejs\node-v22.0.0-win-x64\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:725:5)
2365 verbose stack     at async C:\Users\envy\.gradle\nodejs\node-v22.0.0-win-x64\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:639:7
2365 verbose stack     at async Promise.allSettled (index 464)
2365 verbose stack     at async [reifyPackages] (C:\Users\envy\.gradle\nodejs\node-v22.0.0-win-x64\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:246:11)
2365 verbose stack     at async Arborist.reify (C:\Users\envy\.gradle\nodejs\node-v22.0.0-win-x64\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:165:5)
2365 verbose stack     at async Install.exec (C:\Users\envy\.gradle\nodejs\node-v22.0.0-win-x64\node_modules\npm\lib\commands\install.js:153:5)
2365 verbose stack     at async module.exports (C:\Users\envy\.gradle\nodejs\node-v22.0.0-win-x64\node_modules\npm\lib\cli-entry.js:61:5)                
 
 
The D:\OWJ\androidStudio-mulitplatform\Multiplatform-App\build\js\packages_imported\skiko-wasm-js\0.8.4directory **does** exist
 
As well as the output directory 
 
![Compose-Multiplatform-Wizard-skiko-wasm-js-compile](https://github.com/terrakok/Compose-Multiplatform-Wizard/assets/106614700/e89681a9-bfc3-481f-ac0d-ffb2a5463c55)

**Comment by terrakok** [comment]
outdated
